import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-privacidad',
  templateUrl: './privacidad.component.html',
  styleUrls: ['./privacidad.component.scss']
})
export class PrivacidadComponent implements OnInit {
  privacidad = 'POLÍTICA DE PRIVACIDAD';
  desc1_1 = 'Mediante el presente comunicado ADRIAN GONZALEZ ROMERO le da la bienvenida a su web y le invita a conocer estos términos antes de que facilite cualquiera de sus datos personales en ella.';
  desc1_2 = 'ADRIAN GONZALEZ ROMERO tiene su domicilio fiscal en C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 - VALENCIA y teléfono nº (+34) 630730706; ponemos en conocimiento de los usuarios del sitio web www.arrovacademia.es nuestra política de protección de datos de carácter personal, para que pueda determinar libre y voluntariamente si desean facilitar a ADRIAN GONZALEZ ROMERO los datos personales que se les requieran para poder prestarle los servicios ofertados en su web y que son los propios de su actividad dedicada a la FORMACION NO REGLADA, INCLUIDAS ACTIVIDADES DE REPASO ESCOLAR , ONLINE O PRESENCIALES, así como contestación de cualquier cuestión planteada en relación a sus servicios, para envíos publicitarios, presupuestos que previamente hayan solicitado por cualquier medio, y respuesta a consultas, presupuestos, citas previas u otros con ocasión de la suscripción, registro o cumplimentación de cualquier formulario de datos on-line.';
  desc1_3 = 'La mera visita a este sitio Web no implica que el usuario esté obligado a facilitar ninguna información sobre el mismo.';
  informacion_usuario = 'Información al Usuario';
  desc2_1 = 'ADRIAN GONZALEZ ROMERO (en adelante el RESPONSABLE, ADRIAN GONZALEZ ROMERO o ARROVACADEMIA) es el RESPONSABLE del tratamiento de los datos personales del Usuario de esta web y le informa que dichos datos serán tratados de conformidad con lo dispuesto en el Reglamento (UE) 2016/679 de 27 de abril de 2016 (GDPR)  relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos y resto de normativas vigentes en materia de protección de datos de carácter personal, por lo que se le facilita la siguiente información del tratamiento.';
  menores_edad = 'Menores de edad';
  desc3_1 = 'Para poder ser usuario de esta web deberás ser mayor de 18 años. Por tanto si  fueras menor de esta edad no debes usar esta web, enviarnos datos ni registrarte.';
  desc3_2 = 'En caso de que no se sigan estas instrucciones, la empresa no se hace responsable de los daños y/o perjuicios que pudieran causarse, y del mismo modo repercutirá sobre los padres o tutores legales del/de la menor que actuará, bien por culpa o negligencia, bien por dolo, ya por acción ya por omisión cualquier perjuicio que resulte para la empresa (gastos, sanciones, daños…).';
  desc3_3 = 'Si quieres contactar con nosotros o realizar alguna consulta porque estás interesado/a en nuestros servicios, deberán ser tus padres o tutor/a/es legal/es quienes la realicen.';
  desc3_4 = 'En estos casos solicitaremos datos de tus padres y/o legales representantes, que son datos relativos a las personas de tu familia o entorno, si bien en ningún caso solicitaremos datos relacionados con la situación económica o la intimidad de los otros miembros de la familia o entorno.';
  principios_importantes = 'Algunos principios importantes que debe conocer';
  desc4_1 = 'En contacto@arrovacademia.es es una prioridad el respeto a la protección de los datos personales de los usuarios. Como usuario debe saber que sus derechos están garantizados en esta web.';
  desc4_2 = 'Nos esforzamos en crear un espacio seguro y confiable y por eso deseamos compartir los principios que aplicamos respecto a su privacidad:';
  desc4_3 = '•	Nunca solicitamos información personal a menos que realmente sea necesaria para prestarle los servicios que nos requiera.';
  desc4_4 = '•	Nunca compartimos información personal de los usuarios, excepto para cumplir con la ley o en caso de que se haya autorizado antes de forma expresa.';
  desc4_5 = '•	Nunca utilizamos los datos personales con una finalidad diferente a la expresada en esta política de privacidad.';
  regulaciones = 'Regulaciones legales a las que se acoge esta web';
  desc5_1 = 'ADRIAN GONZALEZ ROMERO ha adecuado esta web a las exigencias del Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de 2016 relativo a la protección de las personas físicas (RGPD), así como con la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico (LSSICE o LSSI). De la misma forma cumplimos con la de la Ley Orgánica (ES) 3/2018, de 5 de diciembre (LOPDGDD).';
  responsable = 'Responsable del tratamiento de tus datos personales';
  desc6_1 = '•	Nombre de dominio: contacto@arrovacademia.es';
  desc6_2 = '•	Nombre comercial: ARROVACADEMIA';
  desc6_3 = '•	Denominación social: ADRIAN GONZALEZ ROMERO';
  desc6_4 = '•	NIF: 29213298D';
  desc6_5 = '•	Domicilio social: C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 - VALENCIA';
  desc6_6 = '•	Teléfono: (+34) 630730706';
  desc6_7 = '•	e-mail: contacto@arrovacademia.es';
  desc6_8 = 'A efectos de lo previsto en el Reglamento General de Protección de Datos, los datos personales que nos envíe a través de los formularios de la web recibirán el nombre de “CONTACTOS” en el Registro de Actividades de Tratamientos. Si Vd. pasa a ser cliente nuestro por utilizar nuestros servicios o comprar nuestros productos, sus datos servirán para gestionar la relación comercial entre las partes y serán tratados en un fichero denominado “CLIENTES Y/O PROVEEDORES”.';
  desc6_9 = 'Para el tratamiento de datos de los usuarios hemos implementado las medidas técnicas, organizativas y de seguridad establecidas en la legislación vigente.';
  caracter_obligatorio = 'Carácter obligatorio o facultativo de la información solicitada al Usuario.';
  desc7_1 = 'Los Usuarios, mediante la marcación de las casillas correspondientes y entrada de datos en los campos, marcados con un asterisco (*) en el formulario de contacto o presentados en formularios, aceptan expresamente y de forma libre e inequívoca, que sus datos son necesarios para atender su petición, por parte de ARROVACADEMIA, siendo totalmente voluntaria la inclusión de datos en los campos restantes.';
  desc7_2 = 'El Usuario garantiza que los datos personales facilitados al RESPONSABLE son veraces y se hace responsable de comunicar cualquier modificación de los mismos.';
  desc7_3 = 'El RESPONSABLE informa y garantiza expresamente a los usuarios que sus datos personales no serán cedidos en ningún caso a terceros, y que siempre que realizara algún tipo de cesión de datos personales, se pedirá previamente el consentimiento expreso, informado e inequívoco por parte los Usuarios.';
  desc7_4 = 'Todos los datos solicitados a través del sitio web son obligatorios, ya que son necesarios para la prestación de un servicio óptimo al Usuario. En caso de que no sean facilitados todos los datos, no se garantiza que la información y servicios facilitados sean completamente ajustados a sus necesidades.';
  obtencion_datos = '¿Cómo obtenemos sus datos?';
  desc8_1 = 'Los datos personales que tratamos en nuestra web pueden proceder de:';
  desc8_2 = '•	Formulario de Valoración';
  desc8_3 = '•	Formulario de Registro';
  finalidad = '¿Con qué finalidad tratamos sus datos personales?';
  desc9_1 = 'Cuando un usuario se conecta con esta web, por ejemplo para mandar un correo al titular o contactar con el mismo, está facilitando información de carácter personal de la que es responsable ARROVACADEMIA Esa información puede incluir datos de carácter personal como puedan ser la dirección IP, nombre, dirección física, dirección de correo electrónico, número de teléfono y otra información. Al facilitar esta información, el usuario da su consentimiento para que su información sea recopilada, utilizada, gestionada y almacenada por ARROVACADEMIA sólo como se describe en el Aviso Legal y en la presente Política de Privacidad.';
  desc9_2 = 'En ARROVACADEMIA existen varios sistemas de captura de información personal y trato la información que facilitan las personas interesadas y usuarios con el siguiente fin:';
  desc9_3 = '•	Formulario de Valoración: En el apartado CURSOS solicitamos determinada información relativa a la formación que pretende contratar y para ello deberá remitirnos la información que le solicitamos a través de la cumplimentación de los formularios habilitados al efecto.  dicha información junto con su mail a través de la web. Así al hacer click en “Enviar Resumen de Información” se enviará el formulario para revisión de nuestros profesores/as y cuando los/as mismos/as lo hayan revisado, recibirás un correo electrónico con la información que necesitas. Estos formularios recogen determinados datos personales, aparte de tu correo electrónico, como puedan ser nivel de estudios, lengua materna…';
  desc9_4 = 'Estos datos podrán ser utilizados para responder a su solicitud y dar respuesta a preguntas y cuestiones sobre contratación de servicios, condiciones de contratación, formas de prestación de servicios, dudas, quejas, comentarios o inquietudes que pueda tener relativas a la información incluida en la web, los servicios que se presten a través de la misma, el tratamiento de sus datos personales, cuestiones referentes a los textos legales incluidos en la web, así como cualesquiera otras consultas que pueda tener y que no estén sujetas a las condiciones de contratación.';
  desc9_5 = 'Una vez tengas claro el curso o formación que necesitas puedes bajarte los formularios de matrícula necesarios para devolvérnoslos escaneados y firmados y una vez verificado el pago, poder comenzar a prestarte nuestros servicios.';
  desc9_6 = '•	Formulario de Registro: Una vez hayas contratado nuestros servicios podrás registrarte; para ello volveremos a solicitarte determinados datos, en concreto tu nombre, apellidos, nombre de usuario, contraseñas para acceso y la fecha de nacimiento (para verificar tu edad) y una vez registrado, recibirás un correo de alta como usuario.';
  desc9_7 = 'Existen otras finalidades por la que tratamos sus datos personales:';
  desc9_8 = '•	Para garantizar el cumplimiento de las condiciones de uso y la ley aplicable. Esto puede incluir el desarrollo de herramientas y algoritmos que ayudan a esta web a garantizar la confidencialidad de los datos personales que recoge.';
  desc9_9 = '•	Para apoyar y mejorar los servicios que ofrece esta web.';
  desc9_10 = '•	También se recogen otros datos no identificativos que se obtienen mediante algunas cookies que se descargan en el ordenador del usuario cuando navega en esta web y que detallamos en la política de cookies.';
  desc9_11 = '•	Para gestionar las redes sociales: ARROVACADEMIA puede tener presencia en redes sociales. El tratamiento de los datos que se lleve a cabo de las  personas que se hagan seguidoras (o fans, amigos…) en las redes sociales de las páginas oficiales de ARROVACADEMIA se regirá por este apartado, así como por aquellas condiciones de uso, políticas de privacidad y normativas de acceso que pertenezcan a la propia red social que proceda en cada caso y aceptadas previamente por el usuario de las mismas para poder parte de la red social que en su caso se trate y formar parte de ARROVACADEMIA en dicha red social.';
  desc9_12 = 'En todo caso ARROVACADEMIA tratará sus datos con las finalidades de administrar correctamente su presencia en la red social de que se trate, informando de actividades, productos o servicios de ARROVACADEMIA, así como para cualquier otra finalidad que las normativas de las redes sociales permitan. En ningún caso utilizaremos los perfiles de seguidores en redes sociales para enviar publicidad de manera individual. Si quiere más información a este respecto puede visitar el apartado publicado en nuestra web POLITICA DE PRIVACIDAD EN RR.SS.';
  desc9_13 = 'ARROVACADEMIA no vende, alquila ni cede datos de carácter personal que puedan identificar al usuario, ni lo hará en el futuro, a terceros, sin el consentimiento previo y expreso. Sin embargo, en algunos casos se pueden realizar colaboraciones con otros profesionales; en esos casos, se requerirá consentimiento a los usuarios informando sobre la identidad del colaborador y la finalidad de la colaboración. Siempre se realizará con los más estrictos estándares de seguridad. Así pues las finalidades del tratamiento serán:';
  desc9_14 = '•	Poder mantener una relación comercial con el Usuario.';
  desc9_15 = '•	Tramitar solicitudes de contratación de servicios';
  desc9_16 = '•	Gestionar su registro de cuenta en nuestra web';
  desc9_17 = '•	Remisión de comunicaciones comerciales publicitarias por email, fax, SMS, MMS, comunidades sociales o cualquier otro medio electrónico o físico, presente o futuro, que posibilite realizar comunicaciones comerciales. Estas comunicaciones serán realizadas por ARROVACADEMIA y relacionadas sobre sus productos y servicios, o de sus colaboradores o proveedores con los que éste haya alcanzado algún acuerdo de promoción. En este caso, los terceros nunca tendrán acceso a los datos personales.';
  desc9_18 = '•	Responder a solicitudes de información, tramitar encargos o cualquier tipo de petición que sea realizada por el usuario a través de cualquiera de las formas de contacto que se ponen a su disposición.';
  desc9_19 = '•	Realizar estudios estadísticos.';
  desc9_20 = 'En caso de que se habilitasen apartados al efecto por parte del RESPONSABLE también podrían tratarse estos datos para:';
  desc9_21 = '•	Remitir el boletín de noticias';
  desc9_22 = '•	Poder participar en el blog de la página web.';
  desc9_23 = 'Por otra forma se informa que en caso de seleccionar como forma de pago el uso de tarjeta de crédito o débito, se le remitirá a una plataforma de pago segura. En estos casos, ADRIAN GONZALEZ ROMERO no tendrá acceso a los datos de dicha tarjeta ya que se dirigen directamente a la compañía que nos presta el servicio.';
  legitimacion = 'Legitimación para el tratamiento de tus datos';
  desc10_1 = 'Para contactar con nosotros a través del formulario y para registrar una cuenta, la base que legitima el uso de sus datos es su consentimiento que se le solicitará con ocasión de cada suscripción o acción que realice.';
  desc10_2 = 'De la misma forma para realizar ofertas prospectivas o comerciales de productos y servicios la base que legitima el uso de sus datos personales es también su consentimiento  que se le solicita, sin que en ningún caso la retirada de este consentimiento condicione la ejecución del contrato de compra de productos o servicios.';
  desc10_3 = 'Para la prestación de nuestros servicios, la base que legitima el uso de sus datos será la relación contractual entre las partes.';
  desc10_4 = 'Si Vd. nos solicita un presupuesto, la base que legitime su confección y envío será la adopción de medidas precontractuales.';
  conservacion_datos = 'Plazo de conservación de los datos: ¿Por cuánto tiempo e conservan los datos?';
  desc11_1 = 'Los datos personales proporcionados se conservarán:';
  desc11_2 = '•	Mientras se mantenga la relación mercantil o de otra naturaleza entre las partes.';
  desc11_3 = '•	No se solicite su supresión por parte del interesado.';
  desc11_4 = 'Así pues se conservarán mientras exista un interés mutuo para mantener el fin/los fines del tratamiento y cuando ya no sea necesario para tal/es fin/es, se suprimirán con medidas de seguridad adecuadas para garantizar la seudonimización de los datos o la destrucción total de los mismos.';
  cesion_datos = 'Cesión de datos: ¿A qué destinatarios se comunicarán los datos?';
  desc12_1 = 'Para prestar servicios estrictamente necesarios para el desarrollo de la actividad, ARROVACADEMIA comparte datos bajo sus correspondientes condiciones de privacidad con los prestadores de servicios más abajo relacionados.';
  desc12_2 = 'Todas las utilidades ofrecidas por terceros son estrictamente necesarias para poder prestarles nuestros servicios a través de esta web y sus prestadores han sido seleccionados atendiendo al cumplimiento de los derechos que preservamos.';
  desc12_3 = 'Dichas empresas tendrán acceso a la información personal necesaria para realizar sus funciones como Encargados de Tratamiento, pero no podrán utilizarla para otros fines. Además, deberán tratar la información personal de conformidad con la presente Política de Privacidad y la legislación aplicable en materia de protección de datos. Son las siguientes:';
  desc12_4 = 'Alojamiento web  y Correo web: ACENS TECHNOLOGIES S.L.U. Más información en www.acens.com.';
  desc12_5 = 'En todo caso los datos que nos facilite estarán protegidos en servidores ubicados en España y por tanto no se realizan transferencias internacionales de datos a estos efectos.';
  desc12_6 = 'En caso de contratar nuestros servicios en la modalidad online, es posible que al utilizar las diferentes aplicaciones o software necesarios para prestar dichos servicios en esta modalidad (por ejemplo software para realización de videoconferencias o uso de aplicaciones de mensajería instantánea) y de los cuales les informaremos oportunamente, se produzcan transferencias internacionales de datos pero en todo caso no actuaremos nosotros como Responsables del Tratamiento toda vez que deberán ser Vds. quienes dispongan de dichas aplicaciones o software y aceptar las condiciones de uso con las compañías que provean las mismas. Nosotros en todo caso les daremos la información de la que dispongamos en el momento previo a contratar y le podremos facilitar enlaces, pero en ningún caso, como ya hemos indicado, actuaremos como RT.';
  desc12_7 = 'Plataforma de pago: REDSYS SERVICIOS DE PROCESAMIENTO S.L. Más información en www.redsys.es.';
  desc12_8 = 'ADRIAN GONZALEZ ROMERO no tendrá acceso a los datos de la tarjeta ya que se dirigen directamente a la compañía que nos presta el servicio.';
  desc12_9 = 'Google Analytics: un servicio analítico de web prestado por Google, Inc., una compañía de Delaware cuya oficina principal está en 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, Estados Unidos (“Google”).';
  desc12_10 = 'Google Analytics utiliza “cookies”, que son archivos de texto ubicados en sus dispositivos para ayudar a analizar el uso que hacen los usuarios del sitio web. La información que generan las cookies acerca del uso de nuestra web (incluyendo su dirección IP) será directamente transmitida y archivada por Google en los servidores de Estados Unidos.';
  desc12_11 = 'Google Adsense: Esta web está asociada a Google para mostrar anuncios a los usuarios que acceden a esta web. Al colaborar con Google, se utilizan cookies para mostrarle anuncios relacionados con sus búsquedas recientes y mostrarle anuncios más relevantes.';
  desc12_12 = 'Se incluyen en este tipo de cookies servicios de terceros como: AdSense, AdWords y Google Analytics, así como una serie de servicios de la marca DoubleClick. Al visitar esta página, se envían cookies procedentes de esos servicios al navegador de su dispositivo. Puede consulta más información sobre los tipos de cookies que utiliza Google, y descubrir  cómo Google utiliza estas cookies pulsando sobre los enlaces (links) subrayados.';
  desc12_13 = 'Así mismo puede utilizar la configuración de anuncios para administrar los anuncios de Google que se le muestran e indicar que no se muestren anuncios basados en sus intereses. Aunque decida no recibir este tipo de anuncios, pueden seguir apareciendo en función de factores como su ubicación general derivada de la dirección. Los servicios de inclusión en directorio  serán gratuitos referenciados en la propia web.';
  desc12_14 = 'ARROVACADEMIA procurará que las fichas y anuncios que aparecen en la Web expresen información veraz y se mantengan actualizadas, si bien no garantiza la exactitud en todo momento de los datos consignados en las mismas.';
  desc12_15 = 'Para poder prestar nuestros servicios online es necesario que Vd. cuente con algún dispositivo automatizado (pc, tablet, Smartphone) en el que tenga acceso a internet y debe tener instaladas las siguientes aplicaciones:';
  desc12_16 = 'Plataforma Video: WHEREBY - VIDEO COMMUNICATION SERVICES AS. Más información en www.whereby.com.';
  desc12_17 = 'Su uso puede conllevar la realización de transferencias internacionales de datos a otros países; esta empresa tiene sede en Noruega y las transferencias internacionales de datos que se realicen están autorizadas por el uso de Cláusulas tipo de protección de datos adoptadas por la Comisión que siguen siendo válidas para transferencias de datos entre países de la UE y fuera de la UE, asumiendo y cumpliendo por tanto la normativa europea en protección de datos personales tal y como se indica en los avisos legales de su web.';
  desc12_18 = 'Aplicación de escritorio remoto: ANYDESK - ANYDESK SOFTWARE GMBH. Más información en www.anydesk.com/es';
  desc12_19 = 'Se le informa que con el uso de dicha aplicación es posible que se produzcan transferencias internacionales de datos, si bien la compañía tiene su sede en EEE, cumpliendo en todo caso con la normativa de privacidad a nivel europeo (RGPD), tal y como se advierte en el la Política de Privacidad del titular de la aplicación.';
  desc12_20 = 'Aplicación de Mensajería: WHATSAPP – WHATSAPP IRELAND LIMITED. Más información en www.whatsapp.com.';
  desc12_21 = 'Si quiere que usemos la aplicación Whatsapp para comunicarnos con Vd., debe autorizarnos. En caso de autorizar su uso, el mismo tiene como finalidad la de gestionar las clases online y nunca para enviar información personal. Dicha información se remitirá a través de listas de distribución (información general) o de forma particular (temas de cada alumno/a). En ningún caso se utilizará para crear grupos. Su uso conlleva la  realización de transferencias internacionales de datos. Si Vd. autoriza su uso, mediante a firma de formulario al efecto Vd. asumirá y autorizará la realización de posibles transferencias internacionales de datos a destinatarios que se encuentren en un país, en un territorio o uno o varios sectores específicos de ese país u organización que no proporcionen un nivel de protección equiparable al que presta la normativa europea de protección de datos.';
  desc12_22 = 'Así mediante la firma de dicho documento específico Vd. declarará haber sido informado/a respecto a la transferencia de datos efectuadas en caso de autorizar el uso de esta aplicación de mensajería instantánea y de que ha sido informado/a claramente de los riesgos del tratamiento debido a la ausencia de garantías apropiadas para la protección de los datos personales existentes en el país de destino y que dichos riesgos consisten en el posible acceso a datos personales por parte de terceros, su posible tratamiento sin su consentimiento, así como que es posible que no pueda ejercer los derechos que la normativa europea concede a los/as interesados/as.';
  datos_navegacion = 'Datos de navegación';
  desc13_1 = 'Al navegar por contacto@arrovacademia.es se pueden recoger datos no identificables, que pueden incluir, direcciones IP, ubicación geográfica (aproximadamente), un registro de cómo se utilizan los servicios y sitios, y otros datos que no pueden ser utilizados para identificar al usuario. Entre los datos no identificativos están también los relacionados con sus hábitos de navegación a través de servicios de terceros. Esta web utiliza los siguientes servicios de análisis de terceros:';
  desc13_2 = '•	Google Analytics.';
  desc13_3 = '•	Search Console.';
  desc13_4 = 'Utilizamos esta información para analizar tendencias, administrar el sitio, rastrear los movimientos de los usuarios alrededor del sitio y para recopilar información demográfica sobre nuestra base de usuarios en su conjunto.';
  derechos_usuario = 'Derechos de los usuarios: ¿Cuáles son sus derechos cuando nos facilita sus datos?';
  desc14_1 = 'Cualquier persona tiene derecho a obtener confirmación sobre si ARROVACADEMIA está tratando datos personales que le conciernen o no.';
  desc14_2 = 'Las personas interesadas tienen derecho a:';
  desc14_3 = '•	Retirar el consentimiento en cualquier momento.';
  desc14_4 = '•	Solicitar el acceso a los datos personales relativos al interesado.';
  desc14_5 = '•	Solicitar su rectificación o supresión.';
  desc14_6 = '•	Solicitar la limitación de su tratamiento.';
  desc14_7 = '•	Oponerse al tratamiento.';
  desc14_8 = '•	Solicitar la portabilidad de los datos.';
  desc14_9 = 'Los interesados podrán acceder a sus datos personales, así como a solicitar la rectificación de datos inexactos o, en su caso, a solicitar su supresión cuando, entre otros motivos, los datos ya no sean necesarios para los fines que fueron recogidos.';
  desc14_10 = 'En determinadas circunstancias, los interesados podrán solicitar la limitación del tratamiento de sus datos, en cuyo caso, únicamente los conservaremos para el ejercicio o la defensa de reclamaciones.';
  desc14_11 = 'En determinadas circunstancias y por motivos relacionados con su situación particular, los interesados podrán oponerse al tratamiento de sus datos. ARROVACADEMIA dejará de tratar los datos, salvo por motivos legítimos imperiosos, o el ejercicio o la defensa de posibles reclamaciones. También podrán solicitar la portabilidad de sus datos.';
  desc14_12 = 'Los interesados también tendrán derecho a la tutela judicial efectiva y a presentar una reclamación ante la autoridad de control, en este caso, la Agencia Española de Protección de Datos, si consideran que el tratamiento de datos personales que le conciernen infringe el Reglamento y/o considera que el tratamiento no se ajusta a la normativa vigente. Dicha reclamación podrá presentarle a través del siguiente enlace web: www.aepd.es, titularidad de la dicha Agencia.';
  desc14_13 = 'En todo caso Vd. puede ejercitar materialmente sus derechos enviando un correo electrónico a la dirección contacto@arrovacademia.es, por teléfono llamando al nº (+34) 630730706o mediante escrito remitido por correo postal a la siguiente dirección: C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 – VALENCIA.';
  secreto = 'Secreto y seguridad de los datos';
  desc15_1 = 'De conformidad con lo dispuesto en el GDPR y la LOPDGDD, ARROVACADEMIA le informa que cumple con todas las disposiciones de dichas normativas para el tratamiento de los datos personales; de la misma forma reconoce su responsabilidad, y manifiestamente con los principios descritos en el GDPR y la LOPDGDD, le informa de que los datos de carácter personal serán  tratados de manera lícita, leal y transparente en relación con el interesado y adecuados, y que dichos datos serán pertinentes y limitados a lo necesario en relación con los fines para los que son tratados.';
  desc15_2 = 'El RESPONSABLE garantiza que ha implementado políticas técnicas y organizativas apropiadas para aplicar las medidas de seguridad que establecen el GDPR y la LOPDGDD con el fin de proteger los derechos y libertades de los Usuarios y les ha comunicado la información adecuada para que puedan ejercerlos.';
  desc15_3 = 'ARROVACADEMIA se compromete en el uso y tratamiento de los datos personales de los usuarios, respetando su confidencialidad y a utilizarlos de acuerdo con la finalidad de los mismos, así como a dar cumplimiento a su obligación de guardarlos y adaptar todas las medidas para evitar la alteración, pérdida, tratamiento y/o acceso no autorizado (como por ejemplo utilizando protocolos “https”, el cifrado de sus datos en el servidor…), de conformidad con lo establecido en la normativa vigente de protección de datos.';
  desc15_4 = 'ARROVACADEMIA no puede garantizar la absoluta inexpugnabilidad de la red de Internet y de los sistemas y por tanto, la violación de los datos mediante accesos fraudulentos a ellos por parte de terceros. En todo caso, caso de producirse la alteración, pérdida, tratamiento y/o acceso no autorizado actuará de acuerdo a las indicaciones de la normativa vigente.';
  exactitud_vericidad = 'Exactitud y veracidad de los datos';
  desc16_1 = 'Como usuario, Vd. es el único responsable de la veracidad y corrección de los datos que remita a ARROVACADEMIA exonerando al mismo de cualquier responsabilidad al respecto.';
  desc16_2 = 'Los usuarios garantizan y responden, en cualquier caso, de la exactitud, vigencia y autenticidad de los datos personales facilitados y se comprometen a mantenerlos debidamente actualizados. El usuario acepta proporcionar información completa y correcta en los formularios que se habiliten en esta web.';
  aceptacion_consentimiento = 'Aceptación y consentimiento';
  desc17_1 = 'El usuario declara haber sido informado de las condiciones sobre protección de datos de carácter personal, aceptando y consintiendo el tratamiento de los mismos por parte de ARROVACADEMIA (contacto@arrovacademia.es) en la forma y para las finalidades indicadas en esta política de privacidad.';
  correos_comerciales = 'Correos comerciales';
  desc18_1 = 'Dado que la dirección de correo electrónico y la dirección postal ordinaria del usuario son datos de carácter personal, cuando dichos datos sean recabados mediante su recogida en el formulario de datos de contacto de la web o por otros medios, de acuerdo con la LSSICE, ARROVACADEMIA no los utilizará para remitirle correos comerciales por vía electrónica que no hayan sido previamente solicitados o autorizados por el usuario (prácticas de SPAM).';
  desc18_2 = 'En consecuencia, en cada uno de los formularios habilitados en la web, el usuario tiene la posibilidad de dar su consentimiento expreso para recibir o no la información, publicidad, ofertas, boletines, newsletter o cualquier otra información comercial, con independencia de la información puntualmente solicitada.';
  desc18_3 = 'Conforme a lo dispuesto en la Ley 34/2002 de Servicios de la Sociedad de la Información y de comercio electrónico, ARROVACADEMIA se compromete a respetar en todo caso las exigencias debidas por dicha normativa, en especial a no enviar comunicaciones de carácter comercial sin identificarlas debidamente. Así pues este tipo de  comunicaciones contendrán la palabra publicidad en el apartado asunto (en el caso de envíos vía correo electrónico) o en el sobre o el soporte que en su caso se trate (en envíos vía correo ordinario) e identificarán claramente a ARROVACADEMIA.';
  desc18_4 = 'No obstante, usted puede revocar en cualquier momento su consentimiento para la recepción de comunicaciones comerciales con la simple notificación a nuestra dirección de correo electrónico contacto@arrovacademia.es, por teléfono llamando al nº (+34) 630730706o mediante escrito remitido por correo postal a la siguiente dirección: C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 – VALENCIA.';
  cambios_politica = 'Cambios en la política de privacidad';
  desc19_1 = 'ARROVACADEMIA se reserva el derecho a modificar la presente política para adaptarla a novedades legislativas y/o jurisprudenciales, así como a las prácticas de autorregulación y/o sectoriales que en su caso considere necesarias, por lo que se aconseja al usuario que la revise periódicamente.';
  desc19_2 = 'Para ello, en dichos supuestos, y aun cuando no exista obligación de preavisar o poner en conocimiento de los usuarios dichas modificaciones, entendiéndose como suficiente con la publicación en el sitio web de ARROVACADEMIA, éste anunciará en esta página los cambios introducidos con razonable antelación a su puesta en práctica. A estos efectos, para una mayor transparencia y comodidad de los usuarios y evitar cualquier tipo de perjuicio a los mismos, ARROVACADEMIA se compromete a que la presente Política de Privacidad contenga siempre la fecha de la última actualización y al mismo tiempo ARROVACADEMIA intentará, cuando lo modifique, sea por la causa que sea, avisar mediante el uso de avisos insertados en la web (capas) de dichas modificaciones.';
  desc19_3 = 'Así pues el contenido de la presente Política de Privacidad, será aplicable y aceptada por el usuario respecto del texto publicado por ARROVACADEMIA en el momento en que el usuario decida rellenar y/o cumplimentar cualquiera de los formularios de contacto que ARROVACADEMIA pone a su disposición para poder prestarle sus servicios y en los cuales se recaben datos de carácter personal.';
  desc19_4 = 'La presente Política de Privacidad ha sido actualizado, por última vez el 15/10/2020.';
  desc19_5 = 'Si el usuario no estuviera conforme, se abstendrá de utilizar la página.';

  constructor() {
  }

  ngOnInit(): void {
  }

}
