import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-aviso-legal',
  templateUrl: './aviso-legal.component.html',
  styleUrls: ['./aviso-legal.component.scss']
})
export class AvisoLegalComponent implements OnInit {
  aviso_legal: string = 'AVISO LEGAL';
  desc1_1: string = 'ADRIAN GONZALEZ ROMERO, responsable del sitio web, en adelante el RESPONSABLE, ADRIAN GONZALEZ ROMERO o ARROVACADEMIA, pone a disposición de los usuarios el presente documento, con el que pretende dar cumplimiento a las obligaciones dispuestas en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSICE), BOE N º 166, así como informar a todos los usuarios del sitio web respecto a cuáles son las condiciones de uso.';
  desc1_2: string = 'Toda persona que acceda a este sitio web asume el papel de usuario, comprometiéndose a la observancia y cumplimiento riguroso de las disposiciones aquí dispuestas, así como a cualquier otra disposición legal que fuera de aplicación.';
  desc1_3: string = 'ADRIAN GONZALEZ ROMERO se reserva el derecho de modificar cualquier tipo de información que pudiera aparecer en el sitio web, sin que exista obligación de preavisar o poner en conocimiento de los usuarios dichas obligaciones, entendiéndose como suficiente con la publicación en el sitio web www.arrovacademia.es';
  datos_identificativos: string = '1. DATOS IDENTIFICATIVOS';
  nombre_dominio: string = 'Nombre de dominio: ';
  dominio: string = 'www.arrovacademia.es';
  nombre_comercial: string = 'Nombre comercial: ';
  nombre: string = 'ARROVACADEMIA';
  denominacion_social: string = 'Denominación social: ';
  denominacion: string = 'ADRIAN GONZALEZ ROMERO';
  nif: string = 'NIF: ';
  numero_nif: string = '29213298D';
  domicilio_social: string = 'Domicilio social: ';
  domicilio: string = 'C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 - VALENCIA';
  telefono: string = 'Teléfono: ';
  numero_telefono: string = '(+34) 630730706';
  email: string = 'e-mail: ';
  email_contacto: string = 'contacto@arrovacademia.es';
  condiciones_generales_uso_y_sitio_web = '2. CONDICIONES GENERALES DE USO Y CONDICIONES DEL SITIO WEB';
  desc2_1: string = 'La presente información regula las condiciones de uso, las limitaciones de responsabilidad y las obligaciones que los usuarios de la página Web, que se publica bajo el nombre del dominio www.arrovacademia.es asumen y se comprometen a respetar.';
  desc2_2: string = 'Se atribuye la condición de USUARIO, a quien acceda y use esta web.';
  desc2_3: string = 'EL usuario por su parte acepta, desde dicho acceso y/o uso, las Condiciones Generales de Uso aquí reflejadas.';
  desc2_4: string = 'Es por ello todos los usuarios se comprometen a la observancia y cumplimiento riguroso de las disposiciones aquí indicadas, así como de cualquier otra disposición legal que fuera de aplicación. Es por ello todos los usuarios se comprometen a la observancia y cumplimiento riguroso de las disposiciones aquí indicadas, así como de cualquier otra disposición legal que fuera de aplicación.';
  desc2_5: string = 'Las citadas Condiciones serán de aplicación independientemente de las Condiciones Generales de Contratación que resulten de obligado cumplimiento y asunción por contratación de servicios o compraventa de productos a través de la web o en modalidad a distancia.';
  desc2_6: string = 'Si el usuario no estuviera conforme, se abstendrá de utilizar la página.';
  desc2_7: string = 'El RESPONSABLE se reserva el derecho de modificar cualquier tipo de información que pudiera aparecer en el sitio web, sin que exista obligación de preavisar o poner en conocimiento de los usuarios dichas obligaciones, entendiéndose como suficiente con la publicación en el sitio web de ARROVACADEMIA, www.arrovacademia.es.';
  desc2_8: string = 'Así pues el contenido del presente Aviso Legal puede sufrir modificaciones, por lo que su aceptación por parte del usuario, será respecto del Aviso Legal publicado por el RESPONSABLE en el momento en que el usuario acceda al sitio Web. Es por ello se aconseja a los usuarios que cada vez que accedan al sitio web, lean atentamente el presente Aviso Legal.';
  desc2_9: string = 'En todo caso, el RESPONSABLE, para una mayor transparencia y comodidad de los usuarios y evitar cualquier tipo de perjuicio a los mismos, el presente Aviso Legal siempre contendrá la fecha de la última actualización y al mismo tiempo el RESPONSABLE intentará, cuando lo modifique, sea por la causa que sea, avisar mediante el uso de avisos insertados en la web (capas) de dichas modificaciones.';
  desc2_10: string = 'El presente Aviso Legal ha sido actualizado por última vez el 15/10/2020';
  desc2_11: string = 'En caso de que cualquier usuario tuviese alguna duda acerca de estas Condiciones legales o cualquier comentario sobre el portal www.arrovacademia.es, por favor diríjase a contacto@arrovacademia.es.';
  desc2_12: string = 'EL USUARIO ASUME LA RESPONSABILIDAD DE USO DEL PORTAL.';
  desc2_13: string = 'www.arrovacademia.es proporciona o puede proporcionar el acceso a diferentes informaciones, servicios, aplicaciones o datos (en adelante “los contenidos”) en Internet pertenecientes al RESPONSABLE o a sus licenciantes, a los que el USUARIO puede tener acceso.';
  desc2_14: string = 'El simple acceso a este sitio web no supone entablar ningún tipo de relación comercial entre ARROVACADEMIA y el usuario.';
  desc2_15: string = 'De hecho esta web no es en forma alguna una tienda online mediante la cual se puedan contratar servicios o adquirir productos a través de la misma. Si Vd. desea contratar nuestros servicios o los productos que puedan promocionarse en esta web, deberá contactar con el RESPONSABLE a través de los medios indicados (por correo postal, teléfono o mail) para que se le informe de los servicios prestados, de las condiciones de contratación y de la forma de prestación de dichos servicios. A estos efectos se le dará a los usuarios y clientes toda la información completa y necesaria.';
  desc2_16: string = 'Con carácter general, el acceso a la información y utilidades del sitio Web no exige una previa suscripción o registro de usuario.';
  desc2_17: string = 'No obstante lo anterior, caso de que fuese necesario para acceder a determinados servicios y/o contenidos, dicha responsabilidad se extiende al registro. En dicho Registro el USUARIO será el RESPONSABLE de aportar información veraz y lícita. El USUARIO se compromete y responsabiliza de mantener toda la información facilitada de forma que responda, en cada momento, a su situación actual.';
  desc2_18: string = 'El tratamiento de los datos de carácter personal suministrados por el usuario se realizará por el RESPONSABLE con sujeción a la Política de Privacidad contenida en este sitio Web. Como consecuencia de este registro, al USUARIO se le puede proporcionar una contraseña de la que será responsable, comprometiéndose a hacer un uso diligente y confidencial de la misma.';
  desc2_19: string = 'El USUARIO está obligado y se compromete a utilizar la página y los contenidos de conformidad con la legislación vigente, el aviso legal, y cualquier otro aviso contenido en esta página, así como con las normas de convivencia, la moral y buenas costumbres generalmente aceptadas y el orden público.';
  desc2_20: string = 'El USUARIO se obliga y se compromete a hacer un uso adecuado de los contenidos y servicios que el RESPONSABLE ofrece o pueda ofrecer a través de su portal (como por ejemplo servicios de chat, foros de discusión o grupos de noticias) y con carácter enunciativo pero no limitativo, a no emplearlos para (I) incurrir en actividades ilícitas, ilegales o contrarias a la buena fe y al orden público; (II) difundir contenidos o propaganda de carácter racista, xenófobo, pornográfico-ilegal, de apología del terrorismo o atentatorio contra los derechos humanos; (III) provocar daños en los sistemas físicos y lógicos de ARROVACADEMIA, de sus proveedores o de terceras personas, introducir o difundir en la red virus informáticos o cualesquiera otros sistemas físicos o lógicos que sean susceptibles de provocar los daños anteriormente mencionados; (IV) intentar acceder y, en su caso, utilizar las cuentas de correo electrónico de otros usuarios y modificar o manipular sus mensajes.';
  desc2_21: string = 'Así mismo, el USUARIO se compromete a no transmitir, difundir o poner a disposición de terceros cualquier contenido en la Página, tales como informaciones, textos, datos, contenidos, mensajes, gráficos, dibujos, archivos de sonido y/o imagen, fotografías, grabaciones, software, logotipos, marcas, iconos, tecnología, fotografías, software, enlaces, diseño gráfico y códigos fuente, o cualquier otro material al que tuviera acceso en su condición de Usuario de la Página, sin que esta enumeración tenga carácter limitativo.';
  desc2_22: string = 'El RESPONSABLE se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren el respeto a la dignidad de la persona, que sean discriminatorios, xenófobos, racistas, pornográficos, que atenten contra la juventud o la infancia, el orden o la seguridad pública o que, a su juicio, no resultaran adecuados para su publicación. En cualquier caso ARROVACADEMIA no será responsable de las opiniones vertidas por los usuarios a través de los foros, chats, u otras herramientas.';
  derechos_propiedad: string = '3. DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL';
  desc3_1: string = 'ARROVACADEMIA por sí o como concesionaria (disponiendo en estos casos de licencia o autorización expresa por parte de los titulares o autores), es titular de todos los contenidos de su web, incluyendo a título enunciativo y sin carácter exhaustivo las imágenes, fotografías, material audiovisual, podcast, textos y/o gráficos, sonidos, audio y video, marcas y/o logotipos, combinaciones de colores, estructura, diseño, programas, software y demás elementos necesarios para su funcionamiento, acceso y uso, edición y compilación. Así pues todos los contenidos del sitio web se encuentran debidamente protegidos las leyes aplicables en la materia (así la ley de marcas y patentes, propiedad intelectual e industrial, derechos de autor…), incluidos los  tratados internacionales en los que España es parte.';
  desc3_2: string = 'En virtud de lo dispuesto en los artículos 8 y 32.1, párrafo segundo, de la Ley de Propiedad Intelectual e independientemente de la finalidad para la que fueran destinados, quedan expresamente prohibidas, incluida su modalidad de puesta a disposición, el uso, explotación, distribución, comunicación pública y/o privada y la comercialización total o parcial de los contenidos de esta página web.';
  desc3_3: string = 'Para poder realizar estas acciones, con cualquier finalidad, en cualquier soporte y por cualquier medio técnico se requerirá en todo caso de la autorización escrita previa y expresa por parte del RESPONSABLE. Cualquier uso no autorizado previamente se considera un incumplimiento grave de los derechos de propiedad intelectual o industrial del autor.';
  desc3_4: string = 'Los diseños, logotipos, texto y/o gráficos ajenos al RESPONSABLE y que pudieran aparecer en el sitio web, pertenecen a sus respectivos propietarios, siendo ellos mismos responsables de cualquier posible controversia que pudiera suscitarse respecto a los mismos. El RESPONSABLE autoriza expresamente a que terceros puedan redirigir directamente a los contenidos concretos del sitio web, y en todo caso redirigir al sitio web principal de www.arrovacademia.es.';
  desc3_5: string = 'El RESPONSABLE reconoce a favor de sus titulares los correspondientes derechos de propiedad intelectual e industrial, no implicando su sola mención o aparición en el sitio web la existencia de derechos o responsabilidad alguna sobre los mismos, como tampoco respaldo, patrocinio o recomendación por parte del mismo.';
  desc3_6: string = 'El USUARIO se compromete a respetar los derechos de Propiedad Intelectual e Industrial titularidad de ARROVACADEMIA y de sus licenciantes y/o autorizantes.';
  desc3_7: string = 'El USUARIO podrá visualizar los elementos del portal e incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte físico siempre y cuando sea única y exclusivamente para su uso personal y privado. El USUARIO deberá abstenerse de suprimir, alterar, eludir o manipular cualquier dispositivo de protección o sistema de seguridad que estuviera instalado en la web de ARROVACADEMIA (www.arrovacademia.es)';
  desc3_8: string = 'Para realizar cualquier tipo de observación respecto a posibles incumplimientos de los derechos de propiedad intelectual o industrial, así como sobre cualquiera de los contenidos del sitio web, puede hacerlo a través del correo electrónico contacto@arrovacademia.es.';
  desc3_9: string = 'En el caso de que un usuario o un tercero consideren que se ha producido una violación de sus legítimos derechos de propiedad intelectual por la introducción de un determinado contenido en la web, deberá notificar dicha circunstancia a ARROVACADEMIA al correo electrónico contacto@arrovacademia.es indicando:';
  desc3_10: string = '•	Datos personales del interesado titular de los derechos presuntamente infringidos, o indicar la representación con la que actúa en caso de que la reclamación la presente un tercero distinto del interesado.';
  desc3_11: string = '•	Señalar los contenidos protegidos por los derechos de propiedad intelectual y su ubicación en la web, la acreditación de los derechos, de propiedad intelectual, señalados y la declaración expresa en la que el interesado se responsabiliza de la veracidad de las informaciones facilitadas en la notificación.';
  exencion_responsabilidades: string = '4. EXENCIÓN DE RESPONSABILIDADES';
  desc4_1: string = 'ARROVACADEMIA no se hace responsable, en ningún caso, de los daños y perjuicios de cualquier naturaleza que pudiera causarse por el uso y acceso al sitio web www.arrovacademia.es.';
  desc4_2: string = 'Respecto a los Contenidos: ARROVACADEMIA no se hace responsable, en ningún caso de los daños y perjuicios de cualquier naturaleza que pudieran ocasionar los errores u omisiones de dichos contenidos.';
  desc4_3: string = 'Los datos, textos, informaciones, imágenes, sonidos o cualquier otra publicación en el sitio web www.arrovacademia.es son mostrados con efectos meramente informativos para todas aquellas personas interesadas en los mismos, sin que su acceso genere relación comercial, contractual o profesional entre los usuarios y ARROVACADEMIA.';
  desc4_4: string = 'En caso de discrepancia entre la información contenida en el sitio Web y la contenida en papel, prevalecerá esta última. Se advierte al usuario que antes de emprender cualquier acción derivada del contenido del sitio Web, proceda a verificar la información obtenida poniéndose en contacto con el departamento de Atención al Cliente mediante correo electrónico a remitir a la siguiente dirección: contacto@arrovacademia.es.';
  desc4_5: string = 'Respecto a la disponibilidad y continuidad: ARROVACADEMIA excluye, con toda la extensión que permite nuestro ordenamiento jurídico, cualquier responsabilidad por los daños y perjuicios de toda naturaleza causados por la falta de disponibilidad o de continuidad del acceso al sitio Web y sus servicios. El acceso a la información y servicios que presta este sitio Web tiene, en principio, una duración indefinida. No obstante, el RESPONSABLE podrá dar por terminada o suspender el acceso a su sitio web en cualquier momento.';
  desc4_6: string = 'Respecto a Virus y Códigos Maliciosos: ARROVACADEMIA excluye, con toda la extensión que permite nuestro ordenamiento jurídico, cualquier responsabilidad por los daños y perjuicios de toda naturaleza que puedan deberse a la presencia de virus u otros códigos maliciosos en los contenidos que puedan producir cualquier tipo de daños en el sistema informático, documentos electrónicos, ficheros de los usuarios o cualquier otro.';
  desc4_7: string = 'Respecto al uso de enlaces (Links): ARROVACADEMIA excluye, con toda la extensión que permite nuestro ordenamiento jurídico, cualquier responsabilidad por los daños y perjuicios de toda naturaleza causados a los usuarios por el uso de dispositivos técnicos de enlaces (links), directorios y herramientas de búsqueda, que permiten a los usuarios acceder a sitios Web pertenecientes y/o gestionados por terceros.';
  desc4_8: string = 'Uso ilícito: ARROVACADEMIA no se hace responsable del incumplimiento de cualquier norma aplicable en que pueda incurrir el usuario en su acceso al sitio Web y/o utilización de las informaciones contenidas en la misma. Tampoco se hace responsable del uso ilegítimo que terceras personas puedan hacer de los nombres comerciales, marcas u otros signos distintivos que, no siendo propiedad de ARROVACADEMIA aparezcan en el sitio Web.';
  politica_enlaces: string = '5. POLITICA DE ENLACES';
  desc5_1: string = 'Desde el sitio web, es posible que se redirija a contenidos de terceros sitios web. Dado que el RESPONSABLE no puede controlar siempre los contenidos introducidos por los terceros en sus respectivos sitios web, no asume ningún tipo de responsabilidad respecto a dichos contenidos. En todo caso, procederá a la retirada inmediata de cualquier contenido que pudiera contravenir la legislación nacional o internacional, la moral o el orden público, procediendo a la retirada inmediata de la redirección a dicho sitio web, poniendo en conocimiento de las autoridades competentes el contenido en cuestión.';
  desc5_2: string = 'El RESPONSABLE no se hace responsable de la información y contenidos almacenados, a título enunciativo pero no limitativo, en foros, chats, generadores de blogs, comentarios, redes sociales o cualquier otro medio que permita a terceros publicar contenidos de forma independiente en la página web del ARROVACADEMIA';
  desc5_3: string = 'Sin embargo, y en cumplimiento de lo dispuesto en los artículos 11 y 16 de la LSSICE, se pone a disposición de todos los usuarios, autoridades y fuerzas de seguridad, colaborando de forma activa en la retirada o, en su caso, bloqueo de todos aquellos contenidos que puedan afectar o contravenir la legislación nacional o internacional, los derechos de terceros o la moral y el orden público. En caso de que el usuario considere que existe en el sitio web algún contenido que pudiera ser susceptible de esta clasificación, se ruega lo notifique de forma inmediata al administrador del sitio web.';
  desc5_4: string = 'Este sitio web ha sido revisado y probado para que funcione correctamente. En principio, puede garantizarse el correcto funcionamiento los 365 días del año, 24 horas al día. Sin embargo, el RESPONSABLE no descarta la posibilidad de que existan ciertos errores de programación, o que acontezcan causas de fuerza mayor, catástrofes naturales, huelgas o circunstancias semejantes que hagan imposible el acceso a la página web.';
  desc5_5: string = 'Enlaces externos';
  desc5_6: string = 'La web www.arrovacademia.es proporciona o puede proporcionar enlaces a otros sitios web propios y contenidos que son propiedad de terceros tales como:';
  desc5_7: string = '•	Herramientas.';
  desc5_8: string = '•	Contenido de otros blogs.';
  desc5_9: string = '•	Publicidad';
  desc5_10: string = 'El único objeto de los enlaces es proporcionar al usuario la posibilidad de acceder a dichos enlaces. ARROVACADEMIA no se responsabiliza en ningún caso de los resultados que puedan derivarse al usuario por acceso a dichos enlaces.';
  desc5_11: string = 'Asimismo, el usuario encontrará dentro de este sitio, páginas, promociones, que acceden a los hábitos de navegación de los usuarios para establecer perfiles. Esta información siempre es anónima y no identifica al usuario.';
  desc5_12: string = 'La información que se proporcione en estos sitios patrocinados y/o enlazados está sujeta a las políticas de privacidad que se utilicen en dichos sitios y no estará sujeta a nuestra política de privacidad.';
  desc5_13: string = 'El usuario que se proponga establecer cualquier dispositivo técnico de enlace desde su sitio web al portal www.arrovacademia.es deberá obtener la autorización previa y escrita de ADRIAN GONZALEZ ROMERO. El establecimiento del enlace no implicará en ningún caso la existencia de relaciones entre ADRIAN GONZALEZ ROMERO y el propietario y/o titular del sitio en el que se establezca el enlace, ni la aceptación o aprobación por parte de ARROVACADEMIA de sus contenidos o servicios.';
  desc5_14: string = 'Política de comentarios';
  desc5_15: string = 'En nuestra web no se permiten realizar comentarios. Si se habilitara esta opción se realizaría bajo las siguientes condiciones:';
  desc5_16: string = '•	No se admitirán comentarios que no estén relacionados con la temática de esta web, que incluyan difamaciones, agravios, insultos, ataques personales o faltas de respeto en general hacia ARROVACADEMIA, el autor o hacia otros miembros. Estos comentarios serán suprimidos por los administradores de la web.';
  desc5_17: string = '•	También serán suprimidos los comentarios que contengan información que sea obviamente engañosa o falsa, así como los comentarios que contengan información personal, como, por ejemplo, domicilios privados o teléfonos y que vulneren nuestra política de protección de datos.';
  desc5_18: string = '•	Se desestimarán, igualmente, aquellos comentarios creados sólo con fines promocionales de una web, persona o colectivo y todo lo que pueda ser considerado spam en general.';
  desc5_19: string = '•	No se permitirán comentarios anónimos, así como aquellos realizados por una misma persona con distintos apodos. No se considerarán tampoco aquellos comentarios que intenten forzar un debate o una toma de postura por otro usuario.';
  desc5_20: string = 'Anuncios patrocinados y publicidad';
  desc5_21: string = 'Esta web ofrece o puede ofrecer a los usuarios contenidos patrocinados y anuncios';
  desc5_22: string = 'Los anuncios permanecerán publicados en el portal hasta que sean eliminados o suspendidos por parte del anunciante o de ADRIAN GONZALEZ ROMERO. En todo caso ARROVACADEMIA no será responsable de que, una vez dados de baja en sus bases de datos, los anuncios continúen siendo indexados en buscadores ajenos a este portal.';
  desc5_23: string = 'Cualquier relación contractual o extracontractual que el usuario formalice con los anunciantes o terceras personas contactadas a través de este portal se entienden realizados única y exclusivamente entre el usuario y el anunciante y/o la tercera persona.';
  desc5_24: string = 'El usuario sabe y acepta que ARROVACADEMIA únicamente actúa como cauce o medio publicitario y que, por tanto, no tiene ningún tipo de responsabilidad sobre los daños o perjuicios de cualquier naturaleza ocasionados con motivo de sus negociaciones, conversaciones y/o relaciones contractuales o extracontractuales con los anunciantes o terceras personas físicas o jurídicas contactadas a través de este portal.';
  cookies: string = '6. USO DE COOKIES';
  desc6_1: string = 'ARROVACADEMIA pretende ofrecerle una navegación más cómoda. A tal fin al igual que se hace en otros sitios web, en este Sitio web se utilizan cookies.';
  desc6_2: string = 'Para que, en su caso, pueda otorgar su consentimiento informado e inequívoco le explicamos, de forma detallada, cómo funcionan nuestras cookies en el apartado POLITICA DE COOKIES. En dicho apartado le indicamos qué son las cookies, el uso que hacemos de ellas y las opciones que tiene para gestionarlas.';
  desc6_3: string = 'El USUARIO tiene la posibilidad de configurar su navegador para ser avisado en pantalla de la recepción de cookies y para impedir la instalación de cookies en su equipo. Por favor, consulte las instrucciones y manuales de su navegador para ampliar esta información. Si rechaza la instalación de cookies podrá seguir usando el sitio Web, aunque el uso de algunos de sus servicios podrá ser limitado.';
  desc6_4: string = 'Al navegar y continuar en nuestro Sitio web estará consintiendo el uso de las cookies, por los plazos señalados en las condiciones contenidas en la referida política de cookies.';
  desc6_5: string = 'Este sitio web puede utilizar cookies técnicas (pequeños archivos de información que el servidor envía al ordenador de quien accede a la página) para llevar a cabo determinadas funciones que son consideradas imprescindibles para el correcto funcionamiento y visualización del sitio. Las cookies utilizadas tienen, en todo caso, carácter temporal, con la única finalidad de hacer más eficaz la navegación, y desaparecen al terminar la sesión del usuario. En ningún caso, estas cookies proporcionan por sí mismas datos de carácter personal y no se utilizarán para la recogida de los mismos.';
  desc6_6: string = 'Mediante el uso de cookies también es posible que el servidor donde se encuentra la web reconozca el navegador utilizado por el usuario con la finalidad de que la navegación sea más sencilla, permitiendo, por ejemplo, el acceso de los usuarios que se hayan registrado previamente a las áreas, servicios, promociones o concursos reservados exclusivamente a ellos sin tener que registrarse en cada visita. También se pueden utilizar para medir la audiencia, parámetros de tráfico, controlar el progreso y número de entradas, etc, siendo en estos casos cookies prescindibles técnicamente pero beneficiosas para el usuario. Este sitio web no instalará cookies prescindibles sin el consentimiento previo del usuario.';
  ip: string = '7. DIRECCIONES IP';
  desc7_1: string = 'Los servidores del sitio web podrán detectar de manera automática la dirección IP y el nombre de dominio utilizados por el usuario. Una dirección IP es un número asignado automáticamente a un ordenador cuando éste se conecta a Internet. Toda esta información es registrada para el tratamiento de datos de actividad del servidor que permite el posterior procesamiento de los datos con el fin de obtener mediciones únicamente estadísticas que permitan conocer el número de impresiones de páginas, el número de visitas realizadas a los servidores web, el orden de visitas, el punto de acceso, etc.';
  notificaciones: string = '8. NOTIFICACIONES';
  desc8_1: string = 'Todas las notificaciones o comunicaciones realizadas por los usuarios a ARROVACADEMIA se considerarán eficaces, a todos los efectos, cuando se dirijan al Servicio de Atención al Cliente por alguna de las siguientes formas:';
  desc8_2: string = '•	Mediante envío postal a la siguiente dirección: C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 – VALENCIA';
  desc8_3: string = '•	Mediante llamada telefónica al nº (+34) 630730706';
  desc8_4: string = '•	Mediante envío de mail al correo electrónico: contacto@arrovacademia.es';
  desc8_5: string = 'De igual forma, todas las notificaciones que realice ARROVACADEMIA al usuario se considerarán eficaces, a todos los efectos, cuando se realicen por alguna de las siguientes formas:';
  desc8_6: string = '•	Mediante envío postal a la dirección que el usuario haya previamente puesto en conocimiento de ARROVACADEMIA.';
  desc8_7: string = '•	Mediante llamada telefónica o fax al número que el usuario haya puesto previamente en conocimiento de ARROVACADEMIA.';
  desc8_8: string = '•	Mediante envío de e-mail a la dirección de correo electrónico que el usuario haya puesto previamente en conocimiento de ARROVACADEMIA.';
  desc8_9: string = 'Por lo tanto, para que estas notificaciones puedan llevarse a efecto es preciso que el usuario manifieste que todos los datos facilitados por él son ciertos y actuales, comprometiéndose a notificar cualquier modificación de los mismos.d';
  proteccion_datos: string = '9. PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL';
  desc9_1: string = 'Ir a Política de Privacidad';
  reclamaciones: string = '10. RECLAMACIONES';
  desc10_1: string = 'ADRIAN GONZALEZ ROMERO informa de que dispone de hojas de reclamación a disposición de los usuarios y clientes de su web. El usuario podrá realizar reclamaciones solicitando su hoja de reclamación   o remitiendo un correo electrónico a contacto@arrovacademia.es indicando su nombre y apellidos, el producto/servicio adquirido y exponiendo los motivos de su reclamación.';
  desc10_2: string = 'El usuario podrá notificarnos la reclamación, bien a través de correo electrónico a contacto@arrovacademia.es, o bien por correo postal dirigido a C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 – VALENCIA.';
  desc10_3: string = 'Para remitirnos su reclamación puede utilizar el siguiente modelo:';
  desc10_4: string = 'A la atención de ADRIAN GONZALEZ ROMERO con domicilio postal en C/ CARMEN DONDERIS, nº 1-38 - MELIANA - 46.133 – VALENCIA o por correo electrónico al mailcontacto@arrovacademia.es. Servicio/Producto Adquirido:';
  desc10_5: string = 'Adquirido el día:';
  desc10_6: string = 'Nombre del usuario:';
  desc10_7: string = 'Domicilio del usuario:';
  desc10_8: string = 'Firma del usuario (solo si se presenta en papel):';
  desc10_9: string = 'Fecha:';
  desc10_10: string = 'Motivo de la reclamación:';
  resolucion_conflictos: string = '11. PLATAFORMA DE RESOLUCIÓN DE CONFLICTOS';
  desc11_1: string = 'ADRIAN GONZALEZ ROMERO pone también a disposición de los usuarios la plataforma de resolución de litigios que facilita la Comisión Europea y que se encuentra disponible en el siguiente enlace: https://ec.europa.eu/consumers/odr/';
  ley: string = '12. LEY APLICABLE Y JURISDICCIÓN';
  desc12_1: string = 'Para la resolución de todas las controversias o cuestiones relacionadas con el presente sitio web o de las actividades en él desarrolladas, será de aplicación la legislación española, a la que se someten expresamente las partes, siendo competentes para la resolución de todos los conflictos derivados o relacionados con su uso los Juzgados y Tribunales de que por ley correspondan al partido judicial de MELIANA (VALENCIA).';

  constructor() { }

  ngOnInit(): void {
  }

}
